# Generated by Django 4.1.5 on 2023-05-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
