# Generated by Django 4.1.5 on 2023-05-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.IntegerField(choices=[(1, '10:00AM - 11:00AM'), (2, '11:00AM - 12:00PM')])),
            ],
        ),
    ]
